apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-kubernetes-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: api-kubernetes
  template:
    metadata:
      labels:
        app: api-kubernetes
    spec:
      containers: 
        - name: api
          image: guilhermesd/apikubernetes:4        