apiVersion: v1
kind: Service
metadata: 
  name: api-kubernetes-service
spec:
  selector:
    app: api-kubernetes
  ports:
    - protocol: 'TCP'
      port: 80
      targetPort: 80
  type: LoadBalancer
